--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 7/2/2020 4:29:15 PM
-- Server version: 5.5.5-10.1.26-MariaDB
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO crud_product.employees(id, name, email, phone, address, description, date) VALUES
(2, 'Mihaela TrempetiÄ‡', 'mihaela.trempetic@gmail.com', 13454545, 'jdfgfdogj dfogh ofd ', 'kladsjflijsdf sdlfj lsdjf sdjf', NULL),
(6, 'Chris Kenjel', 'kris123@gmail.com', 99, 'Blah 4', 'Lorem ipsum dolor sit...', NULL);