--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 7/2/2020 4:29:16 PM
-- Server version: 5.5.5-10.1.26-MariaDB
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO crud_product.user(userid, username, password, firstname, lastname, email) VALUES
(1, 'mickey', 'd41d8cd98f00b204e9800998ecf8427e', 'Mihaela', 'TrempetiÄ‡', 'mihaela.trempetic@gmail.com'),
(2, 'miha', 'd41d8cd98f00b204e9800998ecf8427e', 'Gabriela', 'TrempetiÄ‡', 'mihaela.trempetic@gmail.com'),
(3, 'Mickey099', '202cb962ac59075b964b07152d234b70', 'Mihaela', 'TrempetiÄ‡', 'mihaela.trempetic@gmail.com'),
(46, 'mixy9', '123', 'Mihaela', 'TrempetiÄ‡', 'mihaela.trempetic@gmail.com'),
(47, 'fdg', '202cb962ac59075b964b07152d234b70', 'Mihaela', 'TrempetiÄ‡', 'mihaela.trempetic@gmail.com'),
(51, 'adm', 'c4ca4238a0b923820dcc509a6f75849b', 'Mihaela', 'TrempetiÄ‡', 'mihaela.trempetic@gmail.com'),
(52, 'user1', 'c4ca4238a0b923820dcc509a6f75849b', 'Mihaela', 'TrempetiÄ‡', 'mihaela.trempetic@gmail.com');